language: node_js
os: linux
dist: xenial
node_js: [ 14 ]

install:
  - npm install

script:
  - npm run build
  - for i in dist/*; do tar -czf "$(echo $i | sed 's/\..*//')-x64.tar.gz" --transform 's/^[^\.]*/appmap/' $i; done

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: dist/*.tar.gz
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
